### ISSUE TITLE
illegal argument exception v0.5

### ISSUE THREAD

**Issue by calkan** [vadimzalunin/crammer#4]
Hi

Using v 0.5, I first converted BAM->CRAM (with the read quality mask):

 java -d64 -jar cramtools.jar  cram --input-bam-file  SRR034940.sort.bam --output-cram-file SRR034940.sortv05.cram --reference-fasta-file hg19.fasta --read-quality-mask-file  readmask.pos --capture-unmapped-quality-scores. Question here: I _had to_ read the java code to find the --read-quality-mask and --capture-unmapped-quality-scores parameters. Are these sufficient to keep the unmapped reads? Another question here: I used the readmask.pos file that came in with the package, is this an "officially recommended" RQM file? The documentation on RQM is not comprehensive and clear. My data is 100bp PE human WGS.

When reconverting to BAM from CRAM:
java -d64 -jar cramtools.jar bam --output-bam-file  SRR034940.sortv05.bam --input-cram-file SRR034940.sortv05.cram --reference-fasta-file ~hg19.fasta 

I get:

ERROR Cram2Bam - Offensive SAM record: 32840312 100b unmapped read.
ERROR Cram2Bam - SAM record al start=59033765
Exception in thread "main" java.lang.IllegalArgumentException: Alignments added out of order in SAMFileWriterImpl.addAlignment for SRR034940.sortv05.bam. Sort order is coordinate. Offending records are at [*:0] and [chrY:59033765]
        at net.sf.samtools.SAMFileWriterImpl.assertPresorted(SAMFileWriterImpl.java:164)
        at net.sf.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:154)
        at uk.ac.ebi.ena.sra.cram.Cram2Bam.writeSAMRecord(Cram2Bam.java:342)
        at uk.ac.ebi.ena.sra.cram.Cram2Bam.convert(Cram2Bam.java:308)
        at uk.ac.ebi.ena.sra.cram.Cram2Bam.main(Cram2Bam.java:89)
        at uk.ac.ebi.ena.sra.cram.CramTools.main(CramTools.java:53)

**Comment by vadimzalunin** [comment]
Yes, sorry about misleading documentation, that's my next priority. Meanwhile I've added descriptions to program parameters. 
I'm a bit puzzled by the exception, it implies that a record is out of alignment order, which is odd. Would it be possible to get the BAM file with the reference? Anyway, let me think about this a little...

**Comment by vadimzalunin** [comment]
I've pushed a potential fix for you problem. Could you please give it a go? I'll try to reproduce the issue over here but it make take some time. Thanks!

**Comment by calkan** [comment]
Thanks for the update, but I still have the problem. I posted the BAM file (and the CRAM) to : 
ftp://mesh.gs.washington.edu/pub/cram/

Can

**Comment by vadimzalunin** [comment]
I've pushed the fix. Please give it a try.

**Comment by calkan** [comment]
thanks it seems to be working now. I used the readmask.pos file that was in the zip archive. It seems that it changes most of the quality values to 30 ('?') though, would you recommend this rqm file ?

**Comment by vadimzalunin** [comment]
What happens is that '?' is the default value for lost quality score (this can be changed when you convert a CRAM to BAM). CRAM is a lossy format, that's why you see so many default quality scores in a restored BAM file. 
As to read mask files, may I ask why would you like to use them? The idea here is to provide a way to mask quality scores for each read individually, it means that a mask for each read in the file would have to be provided, not one mask for all reads. 
I would recommend to start with the following quality budget mode: 
--capture-insertion-quality-scores --capture-substitution-quality-scores --capture-unmapped-quality-scores
And see if the result is good enough.

**Comment by calkan** [comment]
Thanks. For the reason why I was using the read mask files, I'd like to blame the previously unavailable documentation :-) I see now that you updated the webpage to describe the parameters. In the previous page there was a statement like "crammer doesn't keep quality scores unless an RQM file was specified", or something to that effect, or I misread it. I'll try with the options you recommend now.

**Comment by vadimzalunin** [comment]
I'm very sorry about misleading/missing documentation. 
I'm closing this issue but please feel free to share your thoughts about CRAM, any feedback would be appreciated.
